name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          
      - name: Create React App
        run: |
          npx create-react-app .
          npm install @tailwindcss/typography tailwindcss postcss autoprefixer --save
        
      - name: Copy Component Files
        run: |
          mkdir -p src/components
          cp -R src/* backup/ || true
          cp -R . source/ || true
          rm -rf src/*
          cp source/src/components/* src/components/ || true
          cp source/src/App.js src/ || true
          cp source/src/index.js src/ || true
          cp source/src/index.css src/ || true
          cp backup/* src/ || true
        
      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build